# Generated by Django 4.2.6 on 2023-10-06 02:04

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("payroll_app", "0004_alter_institution_departments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "days",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (0, "Domingo"),
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miercoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sabado"),
                        ],
                        max_length=13,
                        verbose_name="Dia de la semana",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="employee",
            name="schedule",
        ),
        migrations.AddField(
            model_name="employee",
            name="schedule",
            field=models.ManyToManyField(blank=True, to="payroll_app.schedule"),
        ),
    ]
